import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex  w-full h-screen bg-gray-800 text-white p-10 ">
				<div className="flex flex-col justify-center lg:flex-row w-full max-w-screen-2xl mx-auto">
					<div className="w-screen lg:flex-grow lg:w-2/3 p-10">
						<h2 className="mb-10 font-thin text-xl">
							Are customers satisfied?
						</h2>
						<div className="flex flex-col gap-5">
							<div className="flex justify-between">
								<div className="flex flex-1 text-sm font-semibold text-gray-400">
									Customer
								</div>
								<div className="flex flex-1 text-sm font-semibold text-gray-400">
									Transaction completed
								</div>
								<div className="flex flex-1 text-sm font-semibold text-gray-400">
									Happy
								</div>
								<div className="flex flex-1 text-sm font-semibold text-gray-400">
									Out of 5
								</div>
								<div className="flex flex-1 text-sm font-semibold text-gray-400">
									Review Note
								</div>
							</div>
							<div className="flex justify-between">
								<div className="flex flex-1">Berkay</div>
								<div className="flex flex-1">At 05.05.2022</div>
								<div className="flex flex-1">😁</div>
								<div className="flex flex-1">5/5</div>
								<div className="flex flex-1">It's peeerfect.</div>
							</div>
						</div>
					</div>
					<div className="w-screen lg:w-1/3 h-5/6 p-10">
						<div className="bg-blue-300 text-gray-900 max-w-xl rounded-xl p-10 mx-auto h-full">
							Messages will be here...
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default Home;
