import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Dashboard from "../components/Dashboard";
import MessageBox from "../components/MessageBox";
import MessageInput from "../components/MessageInput";
import useScenario from "../hooks/useScenario";

const Home: NextPage = () => {
	const { setNewScenario, messageBoxID } = useScenario();

	useEffect(() => {
		setNewScenario("hamburger");
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="flex w-full min-h-screen bg-gray-800 text-white p-10 overflow-x-clip">
				<div className="flex flex-col justify-center lg:flex-row lg:w-full lg:max-w-screen-2xl mx-auto">
					<Dashboard />
					<div className="flex flex-col lg:w-1/3 h-5/6">
						<div className="flex my-10">
							<a
								className="text-orange-400 inline-flex items-center ml-4"
								onClick={() => {
									setNewScenario("hamburger");
								}}
							>
								Run scenario
								<svg
									fill="none"
									stroke="currentColor"
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									className="w-4 h-4 ml-2"
									viewBox="0 0 24 24"
								>
									<path d="M5 12h14M12 5l7 7-7 7"></path>
								</svg>
							</a>
						</div>
						<MessageBox messageBoxID={messageBoxID}></MessageBox>
						<MessageInput messageBoxID={messageBoxID}></MessageInput>
					</div>
				</div>
			</div>
		</>
	);
};

export default Home;
